<?php

namespace yeesoft\helpers;

use yii\helpers\ArrayHelper;

/**
 * Menu helper.
 */
class MenuHelper
{

    public static function generateIcon($icon,
                                        $before = '<i class="glyphicon glyphicon-',
                                        $after = '"></i>')
    {
        return $before . $icon . $after;
    }

    public static function getIconsMenu()
    {
        $icons = [];

        foreach (self::getIcons() as $icon => $title) {
            $icons[$icon] = self::generateIcon($icon) . ' ' . $title;
        }

        return ArrayHelper::merge([NULL => 'No Image'], $icons);
    }

    public static function getIcons()
    {
        return [
            '' => 'No Icon',
            'asterisk' => 'Asterisk',
            'plus' => 'Plus',
            'euro' => 'Euro',
            'eur' => 'Eur',
            'minus' => 'Minus',
            'cloud' => 'Cloud',
            'envelope' => 'Envelope',
            'pencil' => 'Pencil',
            'glass' => 'Glass',
            'music' => 'Music',
            'search' => 'Search',
            'heart' => 'Heart',
            'star' => 'Star',
            'star-empty' => 'Star Empty',
            'user' => 'User',
            'film' => 'Film',
            'th-large' => 'Th Large',
            'th' => 'Th',
            'th-list' => 'Th List',
            'ok' => 'Ok',
            'remove' => 'Remove',
            'zoom-in' => 'Zoom In',
            'zoom-out' => 'Zoom Out',
            'off' => 'Off',
            'signal' => 'Signal',
            'cog' => 'Cog',
            'trash' => 'Trash',
            'home' => 'Home',
            'file' => 'File',
            'time' => 'Time',
            'road' => 'Road',
            'download-alt' => 'Download Alt',
            'download' => 'Download',
            'upload' => 'Upload',
            'inbox' => 'Inbox',
            'play-circle' => 'Play Circle',
            'repeat' => 'Repeat',
            'refresh' => 'Refresh',
            'list-alt' => 'List Alt',
            'lock' => 'Lock',
            'flag' => 'Flag',
            'headphones' => 'Headphones',
            'volume-off' => 'Volume Off',
            'volume-down' => 'Volume Down',
            'volume-up' => 'Volume Up',
            'qrcode' => 'Qrcode',
            'barcode' => 'Barcode',
            'tag' => 'Tag',
            'tags' => 'Tags',
            'book' => 'Book',
            'bookmark' => 'Bookmark',
            'print' => 'Print',
            'camera' => 'Camera',
            'font' => 'Font',
            'bold' => 'Bold',
            'italic' => 'Italic',
            'text-height' => 'Text Height',
            'text-width' => 'Text Width',
            'align-left' => 'Align Left',
            'align-center' => 'Align Center',
            'align-right' => 'Align Right',
            'align-justify' => 'Align Justify',
            'list' => 'List',
            'indent-left' => 'Indent Left',
            'indent-right' => 'Indent Right',
            'facetime-video' => 'Facetime Video',
            'picture' => 'Picture',
            'map-marker' => 'Map Marker',
            'adjust' => 'Adjust',
            'tint' => 'Tint',
            'edit' => 'Edit',
            'share' => 'Share',
            'check' => 'Check',
            'move' => 'Move',
            'step-backward' => 'Step Backward',
            'fast-backward' => 'Fast Backward',
            'backward' => 'Backward',
            'play' => 'Play',
            'pause' => 'Pause',
            'stop' => 'Stop',
            'forward' => 'Forward',
            'fast-forward' => 'Fast Forward',
            'step-forward' => 'Step Forward',
            'eject' => 'Eject',
            'chevron-left' => 'Chevron Left',
            'chevron-right' => 'Chevron Right',
            'plus-sign' => 'Plus Sign',
            'minus-sign' => 'Minus Sign',
            'remove-sign' => 'Remove Sign',
            'ok-sign' => 'Ok Sign',
            'question-sign' => 'Question Sign',
            'info-sign' => 'Info Sign',
            'screenshot' => 'Screenshot',
            'remove-circle' => 'Remove Circle',
            'ok-circle' => 'Ok Circle',
            'ban-circle' => 'Ban Circle',
            'arrow-left' => 'Arrow Left',
            'arrow-right' => 'Arrow Right',
            'arrow-up' => 'Arrow Up',
            'arrow-down' => 'Arrow Down',
            'share-alt' => 'Share Alt',
            'resize-full' => 'Resize Full',
            'resize-small' => 'Resize Small',
            'exclamation-sign' => 'Exclamation Sign',
            'gift' => 'Gift',
            'leaf' => 'Leaf',
            'fire' => 'Fire',
            'eye-open' => 'Eye Open',
            'eye-close' => 'Eye Close',
            'warning-sign' => 'Warning Sign',
            'plane' => 'Plane',
            'calendar' => 'Calendar',
            'random' => 'Random',
            'comment' => 'Comment',
            'magnet' => 'Magnet',
            'chevron-up' => 'Chevron Up',
            'chevron-down' => 'Chevron Down',
            'retweet' => 'Retweet',
            'shopping-cart' => 'Shopping Cart',
            'folder-close' => 'Folder Close',
            'folder-open' => 'Folder Open',
            'resize-vertical' => 'Resize Vertical',
            'resize-horizontal' => 'Resize Horizontal',
            'hdd' => 'Hdd',
            'bullhorn' => 'Bullhorn',
            'bell' => 'Bell',
            'certificate' => 'Certificate',
            'thumbs-up' => 'Thumbs Up',
            'thumbs-down' => 'Thumbs Down',
            'hand-right' => 'Hand Right',
            'hand-left' => 'Hand Left',
            'hand-up' => 'Hand Up',
            'hand-down' => 'Hand Down',
            'circle-arrow-right' => 'Circle Arrow Right',
            'circle-arrow-left' => 'Circle Arrow Left',
            'circle-arrow-up' => 'Circle Arrow Up',
            'circle-arrow-down' => 'Circle Arrow Down',
            'globe' => 'Globe',
            'wrench' => 'Wrench',
            'tasks' => 'Tasks',
            'filter' => 'Filter',
            'briefcase' => 'Briefcase',
            'fullscreen' => 'Fullscreen',
            'dashboard' => 'Dashboard',
            'paperclip' => 'Paperclip',
            'heart-empty' => 'Heart Empty',
            'link' => 'Link',
            'phone' => 'Phone',
            'pushpin' => 'Pushpin',
            'usd' => 'Usd',
            'gbp' => 'Gbp',
            'sort' => 'Sort',
            'sort-by-alphabet' => 'Sort By Alphabet',
            'sort-by-alphabet-alt' => 'Sort By Alphabet Alt',
            'sort-by-order' => 'Sort By Order',
            'sort-by-order-alt' => 'Sort By Order Alt',
            'sort-by-attributes' => 'Sort By Attributes',
            'sort-by-attributes-alt' => 'Sort By Attributes Alt',
            'unchecked' => 'Unchecked',
            'expand' => 'Expand',
            'collapse-down' => 'Collapse Down',
            'collapse-up' => 'Collapse Up',
            'log-in' => 'Log In',
            'flash' => 'Flash',
            'log-out' => 'Log Out',
            'new-window' => 'New Window',
            'record' => 'Record',
            'save' => 'Save',
            'open' => 'Open',
            'saved' => 'Saved',
            'import' => 'Import',
            'export' => 'Export',
            'send' => 'Send',
            'floppy-disk' => 'Floppy Disk',
            'floppy-saved' => 'Floppy Saved',
            'floppy-remove' => 'Floppy Remove',
            'floppy-save' => 'Floppy Save',
            'floppy-open' => 'Floppy Open',
            'credit-card' => 'Credit Card',
            'transfer' => 'Transfer',
            'cutlery' => 'Cutlery',
            'header' => 'Header',
            'compressed' => 'Compressed',
            'earphone' => 'Earphone',
            'phone-alt' => 'Phone Alt',
            'tower' => 'Tower',
            'stats' => 'Stats',
            'sd-video' => 'Sd Video',
            'hd-video' => 'Hd Video',
            'subtitles' => 'Subtitles',
            'sound-stereo' => 'Sound Stereo',
            'sound-dolby' => 'Sound Dolby',
            'sound-5-1' => 'Sound 5 1',
            'sound-6-1' => 'Sound 6 1',
            'sound-7-1' => 'Sound 7 1',
            'copyright-mark' => 'Copyright Mark',
            'registration-mark' => 'Registration Mark',
            'cloud-download' => 'Cloud Download',
            'cloud-upload' => 'Cloud Upload',
            'tree-conifer' => 'Tree Conifer',
            'tree-deciduous' => 'Tree Deciduous',
            'cd' => 'Cd',
            'save-file' => 'Save File',
            'open-file' => 'Open File',
            'level-up' => 'Level Up',
            'copy' => 'Copy',
            'paste' => 'Paste',
            'alert' => 'Alert',
            'equalizer' => 'Equalizer',
            'king' => 'King',
            'queen' => 'Queen',
            'pawn' => 'Pawn',
            'bishop' => 'Bishop',
            'knight' => 'Knight',
            'baby-formula' => 'Baby Formula',
            'tent' => 'Tent',
            'blackboard' => 'Blackboard',
            'bed' => 'Bed',
            'apple' => 'Apple',
            'erase' => 'Erase',
            'hourglass' => 'Hourglass',
            'lamp' => 'Lamp',
            'duplicate' => 'Duplicate',
            'piggy-bank' => 'Piggy Bank',
            'scissors' => 'Scissors',
            'bitcoin' => 'Bitcoin',
            'btc' => 'Btc',
            'xbt' => 'Xbt',
            'yen' => 'Yen',
            'jpy' => 'Jpy',
            'ruble' => 'Ruble',
            'rub' => 'Rub',
            'scale' => 'Scale',
            'ice-lolly' => 'Ice Lolly',
            'ice-lolly-tasted' => 'Ice Lolly Tasted',
            'education' => 'Education',
            'option-horizontal' => 'Option Horizontal',
            'option-vertical' => 'Option Vertical',
            'menu-hamburger' => 'Menu Hamburger',
            'modal-window' => 'Modal Window',
            'oil' => 'Oil',
            'grain' => 'Grain',
            'sunglasses' => 'Sunglasses',
            'text-size' => 'Text Size',
            'text-color' => 'Text Color',
            'text-background' => 'Text Background',
            'object-align-top' => 'Object Align Top',
            'object-align-bottom' => 'Object Align Bottom',
            'object-align-horizontal' => 'Object Align Horizontal',
            'object-align-left' => 'Object Align Left',
            'object-align-vertical' => 'Object Align Vertical',
            'object-align-right' => 'Object Align Right',
            'triangle-right' => 'Triangle Right',
            'triangle-left' => 'Triangle Left',
            'triangle-bottom' => 'Triangle Bottom',
            'triangle-top' => 'Triangle Top',
            'console' => 'Console',
            'superscript' => 'Superscript',
            'subscript' => 'Subscript',
            'menu-left' => 'Menu Left',
            'menu-right' => 'Menu Right',
            'menu-down' => 'Menu Down',
            'menu-up' => 'Menu Up',
        ];
    }
}